# Generated by Django 5.2.6 on 2025-10-03 19:53

import django.db.models.deletion
import edu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, validators=[edu.models.validate_not_whitespace])),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu.curso')),
            ],
        ),
    ]
