# Generated by Django 5.2.6 on 2025-10-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='curso',
        ),
    ]
