# Generated by Django 5.2.6 on 2025-10-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_remove_student_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu.curso'),
        ),
    ]
