# Generated by Django 5.2.6 on 2025-10-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_student_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='edu.curso', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='edu.disciplina')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='edu.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'disciplina', 'semestre'), name='unique_student_disciplina_semestre')],
            },
        ),
    ]
